FROM gcr.io/distroless/static-debian12

# GoReleaser automatically injects this based on the platform it's building for
ARG TARGETPLATFORM

# Copy the binaries from the platform-specific subdirectories GoReleaser creates
COPY $TARGETPLATFORM/wavehouse /usr/local/bin/wavehouse

ENTRYPOINT ["/usr/local/bin/wavehouse"]
