version: 2

builds:
  - id: wavehouse
    main: ./cmd/wavehouse
    binary: wavehouse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: wavehouse-api
    main: ./cmd/wavehouse-api
    binary: wavehouse-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: wavehouse-worker
    main: ./cmd/wavehouse-worker
    binary: wavehouse-worker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

dockers:
  - ids: [wavehouse]
    image_templates:
      - "ghcr.io/wave-rf/wavehouse:{{ .Tag }}"
      - "ghcr.io/wave-rf/wavehouse:latest"
    dockerfile: deployments/docker/Dockerfile.wavehouse
    build_flag_templates:
      - "--platform=linux/amd64"

  - ids: [wavehouse-api]
    image_templates:
      - "ghcr.io/wave-rf/wavehouse-api:{{ .Tag }}"
      - "ghcr.io/wave-rf/wavehouse-api:latest"
    dockerfile: deployments/docker/Dockerfile.wavehouse-api
    build_flag_templates:
      - "--platform=linux/amd64"

  - ids: [wavehouse-worker]
    image_templates:
      - "ghcr.io/wave-rf/wavehouse-worker:{{ .Tag }}"
      - "ghcr.io/wave-rf/wavehouse-worker:latest"
    dockerfile: deployments/docker/Dockerfile.wavehouse-worker
    build_flag_templates:
      - "--platform=linux/amd64"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
