#!/usr/bin/env node
// CLI codegen tool: generates TypeScript type definitions from WaveHouse schema.
// Usage: npx wavehouse codegen --url http://localhost:8080 --out ./src/wavehouse.d.ts

import type { TableSchema, ColumnInfo } from "./types.js";

const CLICKHOUSE_TYPE_MAP: Record<string, string> = {
  UInt8: "number",
  UInt16: "number",
  UInt32: "number",
  UInt64: "number",
  Int8: "number",
  Int16: "number",
  Int32: "number",
  Int64: "number",
  Float32: "number",
  Float64: "number",
  Decimal: "number",
  String: "string",
  FixedString: "string",
  UUID: "string",
  Date: "string",
  Date32: "string",
  DateTime: "string",
  DateTime64: "string",
  Bool: "boolean",
  Boolean: "boolean",
  IPv4: "string",
  IPv6: "string",
  Enum8: "string",
  Enum16: "string",
  JSON: "unknown",
  Array: "unknown[]",
  Map: "Record<string, unknown>",
  Tuple: "unknown[]",
};

function chTypeToTS(chType: string): string {
  // Handle Nullable(T)
  const nullable = chType.match(/^Nullable\((.+)\)$/);
  if (nullable) {
    return `${chTypeToTS(nullable[1])} | null`;
  }
  // Handle Array(T)
  const array = chType.match(/^Array\((.+)\)$/);
  if (array) {
    return `${chTypeToTS(array[1])}[]`;
  }
  // Handle LowCardinality(T)
  const lowCard = chType.match(/^LowCardinality\((.+)\)$/);
  if (lowCard) {
    return chTypeToTS(lowCard[1]);
  }
  // Handle Decimal(P,S)
  if (chType.startsWith("Decimal")) return "number";
  // Handle DateTime64(N)
  if (chType.startsWith("DateTime64")) return "string";
  // Handle FixedString(N)
  if (chType.startsWith("FixedString")) return "string";
  // Handle Enum
  if (chType.startsWith("Enum")) return "string";
  // Direct map
  return CLICKHOUSE_TYPE_MAP[chType] ?? "unknown";
}

function generateRowType(schema: TableSchema): string {
  const fields = schema.columns.map((col: ColumnInfo) => {
    const tsType = chTypeToTS(col.type);
    const optional = col.is_nullable ? "?" : "";
    return `  ${col.name}${optional}: ${tsType};`;
  });
  const name = pascalCase(schema.name);
  return `export interface ${name}Row {\n${fields.join("\n")}\n}`;
}

function generateColumnUnion(schema: TableSchema): string {
  const name = pascalCase(schema.name);
  const cols = schema.columns.map((c: ColumnInfo) => `"${c.name}"`).join(" | ");
  return `export type ${name}Columns = ${cols};`;
}

function pascalCase(s: string): string {
  return s
    .split(/[_\-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function generateFile(schemas: TableSchema[]): string {
  const lines: string[] = [
    "// Auto-generated by @wavehouse/sdk codegen.",
    `// Generated at: ${new Date().toISOString()}`,
    "// Do not edit manually.",
    "",
    'import type { QueryBuilder } from "@wavehouse/sdk";',
    "",
  ];

  for (const schema of schemas) {
    lines.push(generateRowType(schema));
    lines.push("");
    lines.push(generateColumnUnion(schema));
    lines.push("");
  }

  // Generate table name union.
  const tableNames = schemas.map((s) => `"${s.name}"`).join(" | ");
  lines.push(`export type WaveHouseTables = ${tableNames || "never"};`);
  lines.push("");

  // Generate table→row type map.
  lines.push("export interface TableRowMap {");
  for (const schema of schemas) {
    const name = pascalCase(schema.name);
    lines.push(`  "${schema.name}": ${name}Row;`);
  }
  lines.push("}");
  lines.push("");

  // Generate table→columns type map.
  lines.push("export interface TableColumnMap {");
  for (const schema of schemas) {
    const name = pascalCase(schema.name);
    lines.push(`  "${schema.name}": ${name}Columns;`);
  }
  lines.push("}");
  lines.push("");

  // Generate typed query builder factory.
  lines.push(
    "/** Create a type-safe query builder for a known table. */"
  );
  lines.push(
    "export function typedQuery<T extends WaveHouseTables>(table: T): QueryBuilder<TableColumnMap[T]> {"
  );
  lines.push('  return new (await import("@wavehouse/sdk")).QueryBuilder();');
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

// --- CLI ---
async function main() {
  const args = process.argv.slice(2);
  const urlIdx = args.indexOf("--url");
  const outIdx = args.indexOf("--out");
  const tokenIdx = args.indexOf("--token");

  if (args[0] !== "codegen" || urlIdx === -1) {
    console.error(
      "Usage: wavehouse codegen --url <base_url> [--out <file>] [--token <jwt>]"
    );
    process.exit(1);
  }

  const baseUrl = args[urlIdx + 1];
  const outPath = outIdx !== -1 ? args[outIdx + 1] : undefined;
  const token = tokenIdx !== -1 ? args[tokenIdx + 1] : undefined;

  const headers: Record<string, string> = {};
  if (token) headers["Authorization"] = `Bearer ${token}`;

  const res = await fetch(`${baseUrl}/v1/schema`, { headers });
  if (!res.ok) {
    console.error(`Failed to fetch schema: ${res.status} ${res.statusText}`);
    process.exit(1);
  }

  const schemas = (await res.json()) as TableSchema[];
  const output = generateFile(schemas);

  if (outPath) {
    const { writeFileSync } = await import("node:fs");
    writeFileSync(outPath, output, "utf-8");
    console.log(`Generated ${schemas.length} table types → ${outPath}`);
  } else {
    console.log(output);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
