FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /wavehouse-worker ./cmd/wavehouse-worker

FROM gcr.io/distroless/static-debian12
COPY --from=builder /wavehouse-worker /wavehouse-worker
COPY config.yaml /config.yaml
ENTRYPOINT ["/wavehouse-worker"]
