FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /wavehouse-api ./cmd/wavehouse-api

FROM gcr.io/distroless/static-debian12
COPY --from=builder /wavehouse-api /wavehouse-api
COPY config.yaml /config.yaml
ENTRYPOINT ["/wavehouse-api"]
