services:
  signoz-clickhouse:
    image: clickhouse/clickhouse-server:latest
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  signoz-query-service:
    image: signoz/query-service:latest
    ports:
      - "8080:8080" # SigNoz internal API
    environment:
      - ClickHouseUrl=tcp://signoz-clickhouse:9000
    depends_on:
      signoz-clickhouse:
        condition: service_healthy

  signoz-ui:
    image: signoz/frontend:latest
    ports:
      - "3301:3301" # Your Dashboard!
    depends_on:
      - signoz-query-service

  signoz-otel-collector:
    image: signoz/signoz-otel-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./signoz-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC (Where WaveHouse sends traces)
    depends_on:
      signoz-clickhouse:
        condition: service_healthy